/*
export enum UserEvent {
  TRADE_IN_DEFINED,
  TRADE_IN_SKIPPED,

  PAYMENT_TYPE_CASH_CHOSEN,
  PAYMENT_TYPE_LEASING_CHOSEN,
  PAYMENT_TYPE_LOAN_CHOSEN,

  INSURANCE_ADDED,
  INSURANCE_SKIPPED,

  CUSTOMER_DETAILS_AUTOMATIC_CHOSEN,
  CUSTOMER_DETAILS_MANUAL_CHOSEN,

  DELIVERY_TYPE_PICKUP_CHOSEN,
  DELIVERY_TYPE_DELIVERY_CHOSEN,

  ORDER_CREATED,
  ORDER_CANCELLED,

  BACK_BUTTON_CLICKED,
}

export enum Step {
  DEALER_CHOOSER,

  TRADE_IN_EXISTS_CHOOSER,
  TRADE_IN_CAR_DEFINITION,
  TRADE_IN_CAR_CONDITION,
  TRADE_IN_CONFIRM_CAR,

  PAYMENT_METHOD_CHOOSER,
  PAYMENT_FINANCING_DETAILS,

  BANKID_AUTHENTICATION,
  CUSTOMER_INFORMATION_INITIAL,
  CUSTOMER_INFORMATION_DETAILS,
  CREDIT_ASSESSMENT_INFORMATION,
  CREDIT_ASSESSMENT_SIGNING,
  CREDIT_ASSESSED,

  INSURANCE_INFORMATION_DEFINITION,
  INSURANCE_ALTERNATIVE_CHOOSER,

  DELIVERY_METHOD,

  FINAL_SUMMARY,
  FINAL_CONFIRMATION,
}
*/

export enum UserEvent {
  CUSTOMER_EDIT = 'CUSTOMER_EDIT',
  CUSTOMER_EMAIL_AND_PHONE_SET = 'CUSTOMER_EMAIL_AND_PHONE_SET',
  CUSTOMER_ADDRESS_BY_SSN_REQUESTED = 'CUSTOMER_ADDRESS_BY_SSN_REQUESTED',
  CUSTOMER_ADDRESS_BY_SSN_SUCCEEDED = 'CUSTOMER_ADDRESS_BY_SSN_SUCCEEDED',
  CUSTOMER_ADDRESS_BY_SSN_FAILED = 'CUSTOMER_ADDRESS_BY_SSN_FAILED',
  CUSTOMER_ADDRESS_SET = 'CUSTOMER_ADDRESS_SET',

  FINANCIAL_EDIT_CLICKED = 'FINANCIAL_EDIT_CLICKED',
  FINANCIAL_CASH_SELECTED = 'FINANCIAL_CASH_SELECTED',
  FINANCIAL_LOAN_SELECTED = 'FINANCIAL_LOAN_SELECTED',
  FINANCIAL_LEASE_SELECTED = 'FINANCIAL_LEASE_SELECTED',
  FINANCIAL_CASH_SET = 'FINANCIAL_CASH_SET',
  FINANCIAL_LEASE_SET = 'FINANCIAL_LEASE_SET',
  FINANCIAL_LOAN_SET = 'FINANCIAL_LOAN_SET',

  FINANCIAL_CREDIT_SCORING_CREATE_CASE_REQUESTED = 'FINANCIAL_CREDIT_SCORING_CREATE_CASE_REQUESTED',
  FINANCIAL_CREDIT_SCORING_CREATE_CASE_SUCCEEDED = 'FINANCIAL_CREDIT_SCORING_CREATE_CASE_SUCCEEDED',
  FINANCIAL_CREDIT_SCORING_CREATE_CASE_FAILED = 'FINANCIAL_CREDIT_SCORING_CREATE_CASE_FAILED',

  FINANCIAL_CREDIT_SCORING_STATUS_QR_REQUESTED = 'FINANCIAL_CREDIT_SCORING_STATUS_QR_REQUESTED',
  FINANCIAL_CREDIT_SCORING_STATUS_QR_SUCCEEDED = 'FINANCIAL_CREDIT_SCORING_STATUS_QR_SUCCEEDED',
  FINANCIAL_CREDIT_SCORING_STATUS_QR_FAILED = 'FINANCIAL_CREDIT_SCORING_STATUS_QR_FAILED',
  FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_REQUESTED = 'FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_REQUESTED',
  FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_SUCCEEDED = 'FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_SUCCEEDED',
  FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_FAILED = 'FINANCIAL_CREDIT_SCORING_STATUS_SAME_DEVICE_FAILED',

  FINANCIAL_CREDIT_SCORING_SIGNING_REQUESTED = 'FINANCIAL_CREDIT_SCORING_SIGNING_REQUESTED',
  FINANCIAL_CREDIT_SCORING_SIGNING_FAILED = 'FINANCIAL_CREDIT_SCORING_SIGNING_FAILED',
  FINANCIAL_CREDIT_SCORING_SIGNING_SIGNED = 'FINANCIAL_CREDIT_SCORING_SIGNING_SIGNED',
  FINANCIAL_CREDIT_SCORING_SIGNING_SCORED = 'FINANCIAL_CREDIT_SCORING_SIGNING_SCORED',

  TRADE_IN_EDIT = 'TRADE_IN_EDIT',
  TRADE_IN_SELECTED = 'TRADE_IN_SELECTED',
  TRADE_IN_SKIPPED = 'TRADE_IN_SKIPPED',
  TRADE_IN_CONDITION_VERY_GOOD_SELECTED = 'TRADE_IN_CONDITION_VERY_GOOD_SELECTED',
  TRADE_IN_CONDITION_GOOD_SELECTED = 'TRADE_IN_CONDITION_GOOD_SELECTED',
  TRADE_IN_CONDITION_OK_SELECTED = 'TRADE_IN_CONDITION_OK_SELECTED',
  TRADE_IN_VALUATION_REQUESTED = 'TRADE_IN_VALUATION_REQUESTED',
  TRADE_IN_VALUATION_SUCCEEDED = 'TRADE_IN_VALUATION_SUCCEEDED',
  TRADE_IN_VALUATION_FAILED = 'TRADE_IN_VALUATION_FAILED',
  TRADE_IN_SET = 'TRADE_IN_SET',

  INSURANCE_EDIT = 'INSURANCE_EDIT',
  INSURANCE_MILEAGE_BETWEEN_0_AND_1000_SELECTED = 'INSURANCE_MILEAGE_BETWEEN_0_AND_1000_SELECTED',
  INSURANCE_MILEAGE_BETWEEN_1000_AND_1500_SELECTED = 'INSURANCE_MILEAGE_BETWEEN_1000_AND_1500_SELECTED',
  INSURANCE_MILEAGE_BETWEEN_1500_AND_2000_SELECTED = 'INSURANCE_MILEAGE_BETWEEN_1500_AND_2000_SELECTED',
  INSURANCE_MILEAGE_BETWEEN_2000_AND_2500_SELECTED = 'INSURANCE_MILEAGE_BETWEEN_2000_AND_2500_SELECTED',
  INSURANCE_MILEAGE_OVER_2500_SELECTED = 'INSURANCE_MILEAGE_OVER_2500_SELECTED',
  INSURANCE_EDIT_MILEAGE = 'INSURANCE_EDIT_MILEAGE',
  INSURANCE_SKIPPED = 'INSURANCE_SKIPPED',
  INSURANCE_SHOW = 'INSURANCE_SHOW',
  INSURANCE_SET = 'INSURANCE_SET',
  INSURANCE_SELECTED = 'INSURANCE_SELECTED',
  INSURANCE_UNSELECTED = 'INSURANCE_UNSELECTED',

  DELIVERY_EDIT = 'DELIVERY_EDIT',
  DELIVERY_DEALER_SELECTED = 'DELIVERY_DEALER_SELECTED',
  DELIVERY_HOME_SELECTED = 'DELIVERY_HOME_SELECTED',
  DELIVERY_DEALER_SET = 'DELIVERY_DEALER_SET',
  DELIVERY_HOME_SET = 'DELIVERY_HOME_SET',

  ACCESSORY_EDIT = 'ACCESSORY_EDIT',
  ACCESSORY_SKIPPED = 'ACCESSORY_SKIPPED',
  ACCESSORY_SELECTED = 'ACCESSORY_SELECTED',
  ACCESSORY_UNSELECTED = 'ACCESSORY_UNSELECTED',

  CENTRAL_STORAGE_EDIT = 'CENTRAL_STORAGE_EDIT',
  CENTRAL_STORAGE_SELECTED = 'CENTRAL_STORAGE_SELECTED',
  CENTRAL_STORAGE_SET = 'CENTRAL_STORAGE_SET',
}

export enum Step {
  CENTRAL_STORAGE = 'CENTRAL_STORAGE',

  CUSTOMER_EMAIL_AND_PHONE = 'CUSTOMER_EMAIL_AND_PHONE',
  CUSTOMER_ADDRESS = 'CUSTOMER_ADDRESS',

  FINANCIAL = 'FINANCIAL',
  FINANCIAL_CREDIT_SCORING = 'FINANCIAL_CREDIT_SCORING',

  TRADE_IN = 'TRADE_IN',
  TRADE_IN_DETAILS = 'TRADE_IN_DETAILS',

  INSURANCE = 'INSURANCE',
  INSURANCE_IF = 'INSURANCE_IF',

  DELIVERY = 'DELIVERY',

  ACCESSORY = 'ACCESSORY',
}

type Listner = (userEvent: UserEvent, currentStep: Step) => void;

const listners: Listner[] = [];

export const registerUserEventListner = (fn: Listner) => {
  listners.push(fn);
};

export const unregisterUserEventListner = (fn: Listner) => {
  const index = listners.findIndex((f) => f === fn);
  if (index > -1) {
    listners.splice(index, 1);
  }
};

const userEvent = (userEvent: UserEvent, currentStep: Step) => {
  listners.forEach((fn) => fn(userEvent, currentStep));
};

export default userEvent;
