on:
  push:
    branches:
      - main

name: Production - Build and Deploy

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build Javascript
        run: |
          npm run build

      - name: Publish package to npm
        run: |
          npm ci
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Use Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Python packages
        run: |
          pip install azure-storage-blob
          pip install aiohttp

      - name: Execute py script and upload files
        run: |
          python3 deploy/deploy.py
        env:
          BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
          UPLOAD_MAP_FILES: false
