on:
  push:
    branches:
      - test

name: Test - Build and Deploy

jobs:
  build-and-deploy:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Javascript packages
        run: |
          npm install

      - name: Build Javascript
        run: |
          npm run build

      - name: Use npm setup
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1'
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package to npm
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Use Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Python packages
        run: |
          pip install azure-storage-blob
          pip install aiohttp

      - name: Execute py script and upload files
        run: |
          python3 deploy/deploy.py
        env:
          BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
          UPLOAD_MAP_FILES: true
